name: Release

on:
  workflow_dispatch:
    inputs:
      VERSION_BUMP:
        description: 'The version bump'
        type: choice
        options:
        - major
        - minor
        - patch
        default: minor
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: 1
    environment: release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

    - name: Setup Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install node packages
      run: yarn install --ci

    - name: Configure git
      run: |
        git config user.name "Uphold"
        git config user.email "bot@uphold.com"

    - name: Generate release
      env:
        NPM_TOKEN: ${{ secrets.RELEASE_NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      run: |
        echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        npm run release -- --increment ${{ github.event.inputs.VERSION_BUMP }} -V
